#lang racket
(provide analysis1_amann.html)
(require SMathML)
(define (H4. #:attr* [attr* '()] #:id [id #f]
             #:switch? [switch? #f] #:auto? [auto? #f] . html*)
  `(,(build-%heading #:present h4-present #:cite heading-cite
                     #:level 4 #:id id #:switch? switch?
                     #:auto? auto?)
    ,attr* . ,html*))
(define analysis1_amann.html
  (TnTmPrelude
   #:title "分析一 (Amann &amp; Escher)"
   #:css "styles.css"
   (H1. "分析一 (Amann &amp; Escher)")
   (H2. "基础")
   (H3. "逻辑基础")
   (H3. "集合")
   (H3. "函数")
   (H3. "关系和运算")
   (H3. "自然数")
   (H3. "可数性")
   (H3. "群和同态")
   (H3. "环, 域和多项式")
   (H3. "有理数")
   (H3. "实数")
   (H3. "复数")
   (H3. "向量空间, 仿射空间和代数")
   (H2. "收敛")
   (H3. "序列的收敛")
   (H3. "实序列和复序列")
   (H3. "赋范向量空间")
   (H3. "单调序列")
   (H3. "无穷极限")
   (H3. "完备性")
   (H3. "级数")
   (H3. "绝对收敛")
   (H3. "幂级数")
   (H2. "连续函数")
   (H3. "连续性")
   (H3. "拓扑基础")
   (H3. "紧致性")
   (H3. "连通性")
   (P "从直觉上来说显然" $RR "中的一个开区间是" (Q "连通的")
      ", 而如果我们去除了其中的一个点它又会变成" (Q "不连通的")
      ". 本节我们要将连通性的这种直觉性概念精确化. "
      "在达成目的的过程之中, 我们又一次发现拓扑学扮演了基础性的角色.")
   (H4. "定义和基本性质")
   (P "一个度量空间" $X "被称为是" (B "连通的")
      ", 如果" $X "不能被表示为两个无交非空开集之并. "
      "因此, " $X "是连通的当且仅当"
      
      )
   (H3. $RR "上的函数")
   (H3. "指数函数和相关函数")
   (H2. "单变元微分")
   (H3. "可微性")
   (H3. "中值定理及其应用")
   (H3. "Taylor定理")
   (H3. "迭代过程")
   (H2. "函数序列")
   (H3. "一致收敛")
   (H3. "函数序列的连续性和可微性")
   (H3. "解析函数")
   (H3. "多项式逼近")
   ))