#lang racket
(provide (all-defined-out))
(require SMathML)
(define (Tm* . x*)
  (map Tm x*))
(define (H3. #:attr* [attr* '()] #:id [id #f]
             #:switch? [switch? #f] #:auto? [auto? #t] . html*)
  `(,(build-%heading #:present h3-present #:cite heading-cite
                     #:level 3 #:id id #:switch? switch?
                     #:auto? auto?)
    ,attr* . ,html*))
(define (H4. #:attr* [attr* '()] #:id [id #f]
             #:switch? [switch? #f] #:auto? [auto? #t] . html*)
  `(,(build-%heading #:present h4-present #:cite heading-cite
                     #:level 4 #:id id #:switch? switch?
                     #:auto? auto?)
    ,attr* . ,html*))
(define (format-num section index)
  (and index
       (format "~a.~a" (cadr (reverse section)) index)))
(define (format-head name section index)
  (let ((num (format-num section index)))
    (if num
        (B name (format "~a. " num))
        (B name ". "))))
(define (Entry name class)
  (define (present %entry attr* . html*)
    (define id (%entry-id %entry))
    (define Attr* (attr*-set attr* 'class class 'id id))
    (define section (%entry-section %entry))
    (define index (%entry-index %entry))
    (define head (format-head name section index))
    `(div ,Attr* ,head . ,html*))
  (define (cite %entry)
    (define id (%entry-id %entry))
    (define href (string-append "#" id))
    (define section (%entry-section %entry))
    (define index (%entry-index %entry))
    (define num (format-num section index))
    (Cite `(a ((href ,href)) ,name ,num)))
  (lambda (#:id [id #f] #:auto? [auto? #t])
    (lambda (#:attr* [attr* '()] . html*)
      (cons (build-%entry #:id id #:auto? auto? #:present present #:cite cite)
            (cons attr* html*)))))
(define-syntax-rule (define-Entry* (id name class) ...)
  (begin (define id (Entry name class))
         ...))
(define-Entry*
  (Lemma "引理" "lemma")
  (Corollary "推论" "corollary")
  (Definition "定义" "definition")
  (Remark "评注" "remark")
  (Theorem "定理" "theorem")
  (Warning "警告" "warning")
  (Example "例子" "example")
  (Proposition "命题" "proposition"))
(define $env (Ms "env"))
(define app*
  (case-lambda
    ((f x) (app f x))
    ((f g . x*) (app f (apply app* g x*)))))
(define $Even (Mi "Even"))
(define (&Even n)
  (app $Even n))
(define $Odd (Mi "Odd"))
(define (&Odd n)
  (app $Odd n))
(define $aleph (Mi "&aleph;"))
(define $aleph_0 (_ $aleph $0))
(define (对于所有的 x p)
  (: "对于所有的" x ",&nbsp;" p))
(define (存在某个 x p)
  (: "存在某个" x ",&nbsp;" p))
(define equivc
  (case-lambda
    ((a) (bra0 a))
    ((a ~) (_ (bra0 a) ~))))
(define &split:2 (&split 2))
(define $mod (Mi "mod"))
(define (@mod n)
  (@ap $mod n))
(define (mod= x y n)
  (&split:2 (&equiv x y) (@mod n)))
(define $var (Ms "var"))
(define (&var p)
  (app $var p))
(define $Var (Ms "Var"))
(define (&Var x)
  (app $Var x))
(define $FVT (Mi "FVT"))
(define (&FVT t)
  (app $FVT t))
(define $FV (Mi "FV"))
(define (&FV p)
  (app $FV p))
(define $epsilonv (Mi "&varepsilon;"))
(define $loves (Mi "loves"))
(define (&loves x y)
  (appl $loves x y))
(define (App f x)
  (ap f (bra0 x)))
(define (Appl f . x*)
  (ap f (bra0 (apply &cm x*))))
(define $cos (Mi "cos"))
(define (Ramsey s t)
  (appl $R s t))
(define $Disj (Mo "&Vee;"))
(define $Conj (Mo "&Wedge;"))
(define-bigop*
  (Disj $Disj)
  (Conj $Conj))
(define (_prime A x)
  (_^ A x $prime))
(define $Fn (Ms "Fn"))
(define (&Fn f . x*)
  (appl $Fn f (apply |[;]| x*)))
(define (|[;]| . x*)
  (bra0 (apply &\; x*)))
(define (_cm A . x*)
  (_ A (apply &cm x*)))
(define $dual (Ms "dual"))
(define (&dual p)
  (APP $dual p))
(define $.
  (Mo "." #:attr* '((lspace "0"))))
(define (∃ . x*)
  (let-values (((x* P*) (split-at-right x* 1)))
    (: $exists (apply &cm x*) $. (car P*))))
(define (∀ . x*)
  (let-values (((x* P*) (split-at-right x* 1)))
    (: $forall (apply &cm x*) $. (car P*))))
(define $exists!
  (Mo "&exist;!" #:attr* '((lspace "0") (rspace "0"))))
(define (∃! . x*)
  (let-values (((x* P*) (split-at-right x* 1)))
    (: $exists! (apply &cm x*) $. (car P*))))
(define $phiv (Mi "&phiv;"))
(define (qstroke x A B)
  (: A (_ $\| x) B))
(define (subst-eval x q p v)
  (&= (&eval (@psubst x q p) v)
      (&eval p (@ext v x (&eval q v)))))
(define Γ $Gamma:normal)
(define Δ $Delta:normal)
(define (deriv^ x . y*)
  (set-attr*
   (apply
    Mtable
    (Mtr (Mtd $) (Mtd x))
    (map (lambda (y)
           (Mtr (Mtd $=) (Mtd y)))
         y*))
   'displaystyle "true"
   'columnalign "center left"))
(define (deriv^0 x . y*)
  (set-attr*
   (apply
    Mtable
    (Mtr (Mtd $) (Mtd x))
    (map2 (lambda (= y)
            (Mtr (Mtd =) (Mtd y)))
          y*))
   'displaystyle "true"
   'columnalign "center left"))
(define todo.svg
  (Svg
   #:attr* '((width "320")
             (height "160")
             (stroke "black")
             (style "display: block; margin: auto;"))
   (Path #:attr* '((x "0")
                   (y "0")
                   (d "M 0 0 h 320 v 160 h -320 z")
                   (fill "none")))
   (Text #:attr* '((x "130") (y "80")) "欠一张图")))
(define ((tcomment #:n [n ""]) . x*)
  (keyword-apply
   Div '(#:attr*) '(((class "tcomment")))
   (B (format "译者注记~a." n)) " " x*))
(define $d:form
  (Mo "d" #:attr* '((lspace "0") (rspace "0"))))
(define (&d x)
  (ap $d:form x))
(define (&d/d y x)
  (&/ (&d y) (&d x)))
(define -- "&mdash;&mdash;")
(define $space:2ex (&space 2))
(define (@@ . x*)
  (apply @ (add-between x* $space:2ex)))
(define (APP . x*)
  (apply : (add-between x* $space:2ex)))
(define $atoms (Ms "atoms"))
(define (&atoms p)
  (app $atoms p))
(define $eval (Ms "eval"))
(define (&eval p v)
  (APP $eval p v))
(define $true (Mi "true"))
(define $false (Mi "false"))
(define $~ (Mo "~"))
(define &~
  (make-op
   $~
   (err0 '&~)
   (lambda (x) (: $~ x))))
(define $!= (Mo "&vDash;"))
(define (!= . x*)
  (let-values (((a* b*) (split-at-right x* 1)))
    (: (apply &cm a*) $!= (car b*))))
(define $!=_M (_ $!= $M))
(define (!=_M . x*)
  (let-values (((a* b*) (split-at-right x* 1)))
    (: (apply &cm a*) $!=_M (car b*))))
(define (G!= . x*)
  (apply != Γ x*))
(define $!- (Mo "&vdash;"))
(define (!- . x*)
  (let-values (((a* b*) (split-at-right x* 1)))
    (: (apply &cm a*) $!- (car b*))))
(define (G!- . x*)
  (apply !- Γ x*))
(define $& (Mo "&amp;"))
(define $\| (Mo "|"))
(define $<-> (Mo "&harr;"))
(define $--> (Mo "&xrarr;"))
(define $\|=> (Mo "|&rArr;"))
(define $o* (Mo "&otimes;"))
(define $NAND (Mo "NAND"))
(define $NOR (Mo "NOR"))
(define $=_M (_ $= $M))
(define $=_M^ (_ $= $M^))
(define $<=/=> (Mo "&nhArr;"))
(define $-->* (&* $-->))
(define $-->^ (&prime $-->))
(define $-->+ (^ $--> $+))
(define-infix*
  (&-->+ $-->+)
  (&-->^ $-->^)
  (&-->* $-->*)
  (&<=/=> $<=/=>)
  (&=_M^ $=_M^)
  (&=_M $=_M)
  (&NAND $NAND)
  (&NOR $NOR)
  (&o* $o*)
  (&\|=> $\|=>)
  (&--> $-->)
  (&conj $conj)
  (&disj $disj)
  (&& $&)
  (&\| $\|)
  (&=> $=>)
  (&<-> $<->))
(define Σ $Sigma:normal)
(define Σ_1 (_ Σ $1))
(define (ext f x v)
  (ap (@\|-> x v) f))
(define $psubst (Ms "psubst"))
(define &psubst
  (case-lambda
    ((s p) (APP $psubst s p))
    ((x q p) (&psubst (@\|=> x q) p))))
(define $not (Mi "not"))
(define (&not x)
  (app $not x))
(define $and (Mi "and"))
(define (&and p q)
  (appl $and p q))
(define $or (Mi "or"))
(define (&or p q)
  (appl $or p q))
(define $termval (Ms "termval"))
(define &termval
  (case-lambda
    ((M v t) (APP $termval M v t))
    ((M v) (APP $termval M v))
    ((M) (APP $termval M))))
(define $holds (Ms "holds"))
(define &holds
  (case-lambda
    ((M v e) (APP $holds M v e))
    ((M v) (APP $holds M v))))
(define $pholds (Ms "pholds"))
(define (&pholds d p)
  (APP $pholds d p))
(define $tsubst (Ms "tsubst"))
(define &tsubst
  (case-lambda
    ((i t) (APP $tsubst i t))
    ((i) (APP $tsubst i))))
(define $subst (Ms "subst"))
(define &subst
  (case-lambda
    ((i p) (APP $subst i p))
    ((i) (APP $subst i))))
(define $eqaxioms (Ms "eqaxioms"))
(define (&eqaxioms Δ)
  (app $eqaxioms Δ))
(define $eqaxiom (Ms "eqaxiom"))
(define (&eqaxiom p)
  (app $eqaxiom p))
(define $functions (Ms "functions"))
(define (&functions p)
  (APP $functions p))
(define $equalitize (Ms "equalitize"))
(define (&equalitize p)
  (app $equalitize p))
(define $walk (Mi "walk"))
(define (&walk env term)
  (appl $walk env term))
(define $apply (Mi "apply"))
(define (&apply f x)
  (appl $apply f x))
(define-@lized-op*
  (@--> &-->)
  (@-->* &-->*)
  (@Var &Var)
  (@holds &holds)
  (@pholds &pholds)
  (@subst &subst)
  (@tsubst &tsubst)
  (@= &=)
  (@termval &termval)
  (@∃ ∃)
  (@∀ ∀)
  (@dual &dual)
  (@compose &compose)
  (@NAND &NAND)
  (@NOR &NOR)
  (@o* &o*)
  (@<=> &<=>)
  (@\|=> &\|=>)
  (@psubst &psubst)
  (@ext ext)
  (@\|-> &\|->)
  (@=> &=>)
  (@conj &conj)
  (@disj &disj)
  (@neg &neg)
  (@c* &c*))
