#lang racket
(provide books.html)
(require SMathML)
(define books.html
  (TmPrelude
   #:title "书籍推荐"
   #:css "styles.css"
   (H1 "书籍推荐")
   (P "原谅我没有进行分类, 严肃的数学书籍, 严肃的文学书籍, 轻小说, 技术书籍, 乃至galgame等都散列在一起. "
      "唯一可以肯定的是, 这些书籍都给我带来了很多的快乐."
      )
   (Ol
    (Li "Finite-Dimensional Vector Spaces &amp; Linear Algebra Problem Book")
    (Li "Naive Set Theory")
    (Li "Linear Algebra (Hoffman &amp; Kunze)")
    (Li "Analysis (Godement)")
    (Li "Structure and Interpretation of Computer Programs")
    (Li "池袋西口公园")
    (Li "痴人之爱 &amp; 食蓼之虫")
    (Li "十三夜 (樋口一叶著, 林文月译)")
    (Li "枕草子 (林文月译)")
    (Li "菊与刀")
    (Li "文学少女")
    (Li "波上的魔术师")
    (Li "圣母在上")
    (Li "消费社会")
    (Li "象征交换与死亡")
    (Li "发达资本主义时代的抒情诗人: 论波德莱尔")
    (Li "游戏的人 (Homo Ludens)")
    (Li "中世纪的秋天")
    (Li "意识形态的崇高客体")
    (Li "Essentials of Programming Languages")
    (Li "美利坚物语 &amp; 法兰西物语")
    (Li "魔法使之夜")
    (Li "动物化的后现代")
    (Li "The Little Schemer")
    (Li "游戏性写实主义的诞生")
    (Li "The CRPG Book")
    (Li "The Seasoned Schemer")
    (Li "The Reasoned Schemer")
    (Li "Software Design for Flexibility")
    (Li "春与修罗")
    (Li "魔法科高校的劣等生")
    (Li "富岳百景 &amp; 越级申诉 &amp; 如是我闻")
    (Li "Proofs and Types")
    (Li "文化模式")
    (Li "人虎传 &amp; 山月记")
    (Li "近月少女的礼仪")
    (Li "柠檬 &amp; 樱花树下")
    (Li "银河铁道之夜")
    (Li "LearningZIL")
    (Li "Category Theory (Steve Awodey)")
    (Li "Computation Structures")
    (Li "Building Problem Solvers")
    (Li "力学概论")
    (Li "数学的建筑")
    (Li "A Survey of Modern Algebra")
    (Li "Beginning Mathematical Logic")
    (Li "Exercises in Analysis (Part 1)")
    (Li "ML for the Working Programming")
    (Li "Purely Functional Data Structures")
    (Li "Programming in Standard ML")
    (Li "Semantics Engineering with PLT Redex")
    (Li "Lectures on the Curry-Howard Isomorphism")
    
    )
   (H1 "在读的书")
   (Ol
    (Li "Algebra: Chapter 0")
    (Li "Category Theory (Steve Awodey)")
    (Li "Lectures on the Curry-Howard Isomorphism")
    (Li "The Little Typer")
    
    )
   (H1 "网页收藏 (待读列表?)")
   (Ol
    (Li (A "UniversalType in Standard ML" #:attr* '((href "http://mlton.org/UniversalType"))))
    (Li (A "An Introduction to Redex with Abstracting Abstract Machines"
           #:attr* '((href "https://dvanhorn.github.io/redex-aam-tutorial/"))))
    (Li (A "Checking Dependent Types with Normalization by Evaluation: A Tutorial"
           #:attr* '((href "https://davidchristiansen.dk/tutorials/nbe/"))))
    )
   ))