#lang racket
(provide (all-defined-out))
(require SMathML)
(define $be (Mi "be"))
(define $be^ (&prime $be))
(define $while (Mi "while"))
(define $do (Mi "do"))
(define $for (Mi "for"))
(define $to (Mi "to"))
(define $emp (Mi "emp"))
(define $dummy (Mi "_"))
(define $wand (Mo "&minus;&#8270;"))
(define $goto (Mi "goto"))
(define $break (Mi "break"))
(define $return (Mi "return"))
(define $throw (Mi "throw"))
(define $catch (Mi "catch"))
(define $try (Mi "try"))
(define $Store (Mi "Store"))
(define $Variable (Mi "Variable"))
(define $fin (Mi "fin"))
(define $Int (Mi "Int"))
(define $begin (Mi "begin"))
(define $end (Mi "end"))
(define $skip (Mi "skip"))
(define $not (Mi "not"))
(define $and (Mi "and"))
(define $->^fin (^ $-> $fin))
(define $mod (Mi "mod"))
(define $32 (Mn "32"))
(define $2^32 (^ $2 $32))
