#lang racket
(provide (all-defined-out))
(require SMathML)
(define $sqcap (Mo "&sqcap;"))
(define i.sqcap (Mi "&sqcap;"))
(define i.- (Mi "&minus;"))
(define i.<= (Mi "&le;"))
(define i.disj (Mi "&or;"))
(define i.conj (Mi "&and;"))
(define i.neg (Mi "&not;"))
(define i.<-> (Mi "&harr;"))
(define $<-> (Mo "&harr;"))
(define $NJ (Mi "NJ"))
(define (&<-> a b)
  (Mrow a $<-> b))
(define $sqcup (Mo "&sqcup;"))
(define i.sqcup (Mi "&sqcup;"))
(define i.-> (Mi "&rarr;"))
(define (val x) (_ (&db0 x) $v))
(define (val0 x v) (_ (&db0 x) v))
(define $PV (Mi "PV"))
(define $c^^ (&Prime $c))
(define $. (Mi "."))
(define $phantom. (Mphantom $.))
(define (&lam x . x*M)
  (let-values (((x* M*) (split-at-right x*M 1)))
    (let ((M (car M*)))
      (if (null? x*)
          (: $lambda x $phantom. M)
          (: $lambda (apply : x x*) $. M)))))
(define (&lam0 x M)
  (: $lambda x M))
(define (&lam1 x M)
  (: $lambda x $. M))
(define (subst P x Q)
  (: P (bra0 (&:= x Q))))
(define NF (Mi "NF"))
(define NF_beta (_ NF $beta))
(define $->> (Mo "&Rarr;"))
(define $->>beta (_ $->> $beta))
(define i.+ (Mi "+"))
(define $->beta+ (_^ $-> $beta i.+))
(define $=beta (_ $= $beta))
(define (G!- #:env [env $Gamma:normal] . x*)
  (let-values (((b* x*) (split-at-right x* 1)))
    (&entailL (apply &cm env b*) (car x*))))
(define (!- . x*)
  (let-values (((b* x*) (split-at-right x* 1)))
    (&entailL (apply &cm b*) (car x*))))
(define (&label x . t*)
  (Table #:attr* '((class "label") (align "center"))
         (Tr (Td #:attr* '((align "center")) x))
         (Tr (keyword-apply
              Td '(#:attr*) '(((align "center")))
              t*))))
(define $sc (Mo "&sc;"))
(define i.sc (Mi "&sc;"))
(define $->beta (_ $-> $beta))
(define (&if P Q R)
  (: "if&nbsp;" P "&nbsp;then&nbsp;" Q "&nbsp;else&nbsp;" R))
(define $true (Mi "true"))
(define $false (Mi "false"))
(define lam:true (&lam $x $y $x))
(define lam:false (&lam $x $y $y))
(define $0-bold
  (Mn "0" #:attr* '((mathvariant "bold"))))
(define $1-bold
  (Mn "1" #:attr* '((mathvariant "bold"))))
(define $2-bold
  (Mn "2" #:attr* '((mathvariant "bold"))))
(define i.succ (Mi "succ"))
(define i.add (Mi "add"))
(define i.mult (Mi "mult"))
(define i.exp (Mi "exp"))
(define i.zero (Mi "zero"))
(define $FV (Mi "FV"))
(define (&FV M)
  (app $FV M))
(define lambda-> (_ $lambda i.->))
(define (@lam x . x*M)
  (@ (apply &lam x x*M)))
(define (@lam0 x M)
  (@ (&lam0 x M)))
(define (@lam1 x M)
  (@ (&lam1 x M)))
(define $=> (Mo "&rArr;"))
(define $=>beta (_ $=> $beta))
(define $=alpha (_ $= $alpha))
(define Lambda- (^ $Lambda:normal i.-))
(define i.ext (Mi "ext"))
(define $=ext (_ $= i.ext))
(define (eqc X ~)
  (_ (bra0 X) ~))
(define $=beta-eta
  (_ $= (: $beta $eta)))
(define $WN (Mi "WN"))
(define $WN_beta (_ $WN $beta))
(define $SN (Mi "SN"))
(define $SN_beta (_ $SN $beta))
(define $inf_beta (_ $inf $beta))
(define $->small
  (Mo "&rarr;" #:attr* '((scriptlevel "+1"))))
(define (&vec x)
  (^^ x $->small))
(define $l->beta
  (_ (^^ $-> $l) $beta))
(define $h->beta
  (_ (^^ $-> $h) $beta))
(define $i->beta
  (_ (^^ $-> $i) $beta))
(define $Phi->
  (_ $Phi:normal i.->))
(define $dom (Mi "dom"))
(define (&dom f)
  (app $dom f))
(define $rg (Mi "rg"))
(define (&rg f)
  (app $rg f))
(define (@-> . p*)
  (@ (apply &-> p*)))
(define Mx:=N
  (subst $M $x $N))
(define $G:env $Gamma:normal)
(define $G:env^
  (&prime $G:env))
(define $G:env_1
  (_ $G:env $1))
(define $G:env_2
  (_ $G:env $2))
(define (&G:env x)
  (app $G:env x))
(define $thetav
  (Mi "&thetav;"))
(define $~
  (Mo "&Tilde;"))
(define $~G
  (_ $~ $G:env))
(define-infix*
  (&sqcap $sqcap)
  (&sqcup $sqcup)
  (&disj $disj)
  (&conj $conj)
  (&sc $sc)
  (&->beta $->beta)
  (&->>beta $->>beta)
  (&=beta $=beta)
  (&vert $lv)
  (&::= $::=)
  (&=alpha $=alpha)
  (&=> $=>)
  (&=>beta $=>beta)
  (&=ext $=ext)
  (&=beta-eta $=beta-eta)
  (&l->beta $l->beta)
  (&h->beta $h->beta)
  (&i->beta $i->beta)
  (&~ $~)
  (&~G $~G)
  )
(define GMt
  (G!- (&: $M $tau)))
(define (@: . x*)
  (@ (apply &: x*)))
(define (subst* M . xN*)
  (if (null? xN*)
      M
      (apply subst* (subst M (car xN*) (cadr xN*))
             (cddr xN*))))
(define Tstyle1
  (Ttable
   (lambda (d i j)
     (cond ((= j 0) (set-attr* d 'columnalign "right"))
           ((= j 2) (set-attr* d 'columnalign "left"))
           (else d)))))
(define (Cite0 #:attr* [attr* '()] . id*)
  `(cite ,attr* . ,(fenced (map Ref id*))))
(define (default-entry:bib-present %entry:bib attr* . xml*)
  (define index (%entry-index %entry:bib))
  (define numbering (format "[~s] " index))
  (define id (%entry-id %entry:bib))
  (keyword-apply
   Div '(#:attr*) (list (attr*-set attr* 'class "bibliography" 'id id))
   numbering xml*))
(define (default-entry:bib-cite %entry:bib)
  (define id (%entry-id %entry:bib))
  (define index (%entry-index %entry:bib))
  (define numbering (format "~s" index))
  (define href (string-append "#" id))
  `(a ((href ,href)) ,numbering))
(define (build-%entry:bib id)
  (build-%entry #:local? #f #:class "bibliography" #:id id
                #:present default-entry:bib-present
                #:cite default-entry:bib-cite))
(define (Bib #:id [id #f] #:attr* [attr* '()] . xml*)
  `(,(build-%entry:bib id) ,attr* . ,xml*))
(define (format-numbering section index)
  (define sec (cdr (reverse (cons index section))))
  (define numbering
    (apply string-append
           (add-between (map number->string sec) ".")))
  numbering)
(define (format-section section level)
  (define sec (cdr (reverse section)))
  (define numbering
    (apply string-append
           (add-between (map number->string sec) ".")))
  (cond ((= level 2) (format "第~a章" numbering))
        ((= level 3) (format "第~a节" numbering))
        ((= level 4) (format "第~a小节" numbering))
        (else (error 'format-section "invalid level ~s" level))))
(define (default-heading0-present %heading0 attr* . xml*)
  (define level (%heading-level %heading0))
  (define auto? (%heading-auto? %heading0))
  (define section (%heading-section %heading0))
  (define id (%heading-id %heading0))
  (if (<= 2 level 4)
      (let ((tag (string->symbol (format "h~s" level))))
        (if auto?
            `(,tag ,(attr*-set attr* 'id id) ,(format-section section level)
                   " " . ,xml*)
            `(,tag ,(attr*-set attr* 'id id) . ,xml*)))
      (error 'default-heading0-present "invalid level ~s" level)))
(define (default-heading0-cite %heading0)
  (define id (%heading-id %heading0))
  (define href (string-append "#" id))
  (define auto? (%heading-auto? %heading0))
  (define level (%heading-level %heading0))
  (define section (%heading-section %heading0))
  (if auto?
      `(a ((href ,href)) ,(format-section section level))
      (if section
          `(a ((href ,href)) ,section)
          `(a ((href ,href)) ,id))))
(define (build-%heading0 level auto? id section)
  (build-%heading #:level level #:auto? auto? #:id id #:section section
                  #:present default-heading0-present
                  #:cite default-heading0-cite))
(define (Heading0 #:level [level 2] #:auto? [auto? #t] #:id [id #f] #:section [section #f]
                  #:attr* [attr* '()] . xml*)
  `(,(build-%heading0 level auto? id section) ,attr* . ,xml*))
(define (Cite1 #:attr* [attr* '()] id)
  `(cite ,attr* ,(Ref id)))
(define (build-%entry:_ id auto? index present cite)
  (build-%entry #:id id #:auto? auto? #:index index #:present present #:cite cite))
(define (make-entry:_ class name)
  (define (_-present %entry:_ attr* . xml*)
    (define auto? (%entry-auto? %entry:_))
    (define id (%entry-id %entry:_))
    (define Attr*
      (attr*-set attr* 'class class 'id id))
    (define section (%entry-section %entry:_))
    (define index (%entry-index %entry:_))
    (if auto?
        (let* ((n (format-numbering section index))
               (head (format "~a." n)))
          `(div ,Attr* ,(B head " " name ".") " " . ,xml*))
        `(div ,Attr* (b () ,name ".") " " . ,xml*)))
  (define (_-cite %entry:_)
    (define auto? (%entry-auto? %entry:_))
    (define id (%entry-id %entry:_))
    (define href (string-append "#" id))
    (define section (%entry-section %entry:_))
    (define index (%entry-index %entry:_))
    (if auto?
        (if (pair? section) ;section may be a list, a string, or #f.
            `(a ((href ,href)) ,name ,(format-numbering section index))
            (if (string? section)
                `(a ((href ,href))
                    ,section ,(format "的~a~s" name index))
                `(a ((href ,href)) ,(format "某~a~s" name index))))
        (if index
            `(a ((href ,href)) ,index)
            `(a ((href ,href)) ,id))))
  (lambda (#:id [id #f] #:auto? [auto? #t] #:index [index #f])
    (lambda (#:attr* [attr* '()] . xml*)
      (cons (build-%entry:_ id auto? index _-present _-cite)
            (cons attr* xml*)))))
(define-syntax-rule (define-entry:_* (id class name) ...)
  (begin (define id (make-entry:_ class name))
         ...))
(define-entry:_*
  (Definition "definition" "定义")
  (Remark "remark" "评注")
  (Theorem "theorem" "定理")
  (Example "example" "例子")
  (Convention "convention" "约定")
  (Lemma "lemma" "引理")
  
  )