#lang racket
(provide hott.html)
(require SMathML)
(define (heading-present %heading attr* . html*)
  (define level (%heading-level %heading))
  (define auto? (%heading-auto? %heading))
  (define section (%heading-section %heading))
  (define id (%heading-id %heading))
  (cond ((= level 4) `(h4 ,(attr*-set attr* 'id id)
                          ,(format "第~a小节 " (format-section section))
                          . ,html*))
        ((= level 3) `(h3 ,(attr*-set attr* 'id id)
                          ,(format "第~a节 " (format-section section))
                          . ,html*))
        ((= level 2) `(h2 ,(attr*-set attr* 'id id)
                          ,(format "第~a章 " (format-section section))
                          . ,html*))
        ((= level 1) `(h1 ,attr* . ,html*))
        (else (error 'heading-present "invalid level ~s" level))))
(define (format-section section)
  (define sec (cdr (reverse section)))
  (apply string-append
         (add-between (map number->string sec) ".")))
(define (H1 #:attr* [attr* '()] . html*)
  `(,(build-%heading #:present heading-present #:level 1)
    ,attr* . ,html*))
(define (H2 #:attr* [attr* '()] . html*)
  `(,(build-%heading #:present heading-present #:level 2)
    ,attr* . ,html*))
(define (H3 #:attr* [attr* '()] . html*)
  `(,(build-%heading #:present heading-present #:level 3)
    ,attr* . ,html*))
(define (H4 #:attr* [attr* '()] . html*)
  `(,(build-%heading #:present heading-present #:level 4)
    ,attr* . ,html*))
(define hott.html
  (TnTmPrelude
   #:title "同伦类型论"
   #:css "styles.css"
   (H1 "同伦类型论")
   (H2 "类型论")
   (H3 "类型论和集合论的对比")
   (H3 "函数类型")
   (H3 "宇宙和族")
   (H3 "依赖函数类型 (" $Pi:normal "类型)")
   (H3 "积类型")
   (H3 "依赖序对类型 (" $Sigma:normal "类型)")
   (H3 "余积类型")
   (H3 "布尔的类型")
   (H3 "自然数")
   (H3 "模式匹配和递归")
   (H3 "命题作为类型")
   (H3 "相等类型")
   (H2 "同伦类型论")
   (H3 "类型是高阶群胚")
   (H3 "函数是函子")
   (H3 "类型族是纤维")
   (H3 "同伦和等价")
   
   (H2 "集合和逻辑")
   (H2 "等价")
   (H2 "归纳")
   (H2 "高阶归纳类型")
   (H2 "同伦" $n "类型")
   
   ))