#lang racket
(provide lapb.html)
(require SMathML)
(define (H3. . html*)
  `(,(build-%entry #:local? #f #:present H3.present) () . ,html*))
(define (H3.present %entry attr* . html*)
  (define index (%entry-index %entry))
  `(h3 () ,(format "~s. " index) . ,html*))
(define ((Problem) #:attr* [attr* '()] . html*)
  (cons (build-%entry #:local? #f #:class "problem" #:present problem-present)
        (cons attr* html*)))
(define (problem-present %entry attr* . html*)
  (define index (%entry-index %entry))
  `(div ,(attr*-set attr* 'class "problem")
        ,(B (format "题目~s. " index)) . ,html*))
(define (map2 proc lst)
  (if (null? lst)
      '()
      (cons (proc (car lst) (cadr lst))
            (map2 proc (cddr lst)))))
(define (LC . kv*)
  (apply &+ (map2 &i* kv*)))
(define $box+ (Mo "&boxplus;"))
(define $box* (Mo "&boxtimes;"))
(define-infix*
  (&box+ $box+)
  (&box* $box*)
  )
(define lapb.html
  (TnTmPrelude
   #:title "线性代数问题书"
   #:css "styles.css"
   (H1. "线性代数问题书")
   (P "本书为Paul Halmos所写, 其可以被视为他的Finite-Dimensional Vector Spaces的补充.")
   (H2 "前言")
   (H2. "标量")
   (H3. "双加")
   ((Problem)
    "如果实数的一个新的加法 (记之以临时符号" $box+ ") 由"
    (MB (&= (&box+ $alpha $beta) (LC $2 $alpha $2 $beta)))
    "定义, 那么" $box+ "是结合的吗?")
   (H3. "半双加")
   ((Problem)
    )
   (H3. "幂")
   ((Problem)
    )
   (H3. "复数")
   ((Problem)
    "如果一个对于实数序对的运算 (记之以临时符号" $box* ") 由"
    (MB (&= (&box* (tu0 $alpha $beta)
                   (tu0 $gamma $delta))
            (tu0 (&- (&i* $alpha $gamma) (&i* $beta $delta))
                 (&+ (&i* $alpha $delta) (&i* $beta $gamma)))))
    "定义, 那么它是交换的吗, 它是结合的吗?")
   (H3. "仿射变换")
   ((Problem)
    )
   (H3. "矩阵乘法")
   (H3. "模乘法")
   (H3. "小运算")
   (H3. "恒等元素")
   (H3. "复逆")
   (H2. "向量")
   (H2. "基")
   (H2. "变换")
   (H2. "对偶")
   (H2. "相似")
   (H2. "标准形式")
   (H2. "内积空间")
   (H2. "正规性")
   ))