#lang racket
(provide lem_editor.html)
(require SMathML)
(define (Item x t)
  (Li (Code x) ": " t))
(define lem_editor.html
  (Prelude
   #:title "Lem编辑器使用笔记"
   #:css "styles.css"
   (H1 "Lem编辑器使用笔记")
   (P "Lem编辑器是一个类Emacs编辑器, 但是使用Common Lisp作为其扩展语言.")
   (H2 "默认情况下的常用快捷键")
   (Ul (Item "M-x" "执行命令")
       (Item "Tab" "补全 (例如输入路径或者命令时)")
       (Item "C-x C-s" "保存当前缓冲区")
       (Item "C-x C-f" "打开文件")
       (Item "C-x C-w" "写入文件")
       (Item "C-+" "增大字号")
       (Item "C--" "缩小字号")
       (Item "C-s" "搜索")
       (Item "M-g" "行号跳转")
       (Item "M-<" "跳转至缓冲区开头")
       (Item "M->" "跳转至缓冲区末尾")
       (Item "M-w" "复制")
       (Item "C-w" "剪贴")
       (Item "C-y" "粘贴")
       (Item "C-x k" "关闭缓冲区")
       (Item "C-x b" "切换/新建缓冲区")
       (Item "C-x C-b" "列出所有缓冲区 (并可选择切换)")
       (Item "C-x Left" "切换至前一个缓冲区")
       (Item "C-x Right" "切换至后一个缓冲区")
       (Item "C-x 2" "上下分屏")
       (Item "C-x 3" "左右分屏")
       (Item "C-x 1" "删除其他所有窗口")
       (Item "C-x 0" "删除当前窗口")
       (Item "M-:" "对于Common Lisp表达式求值")
       (Item "C-x C-c" "退出Lem编辑器")
       
       )
   (H2 "默认情况下的常用命令")
   (Ul (Item "find-file" "打开文件")
       (Item "write-file" "写入文件")
       (Item "start-lisp-repl" "打开Common Lisp的REPL")
       (Item "toggle-line-numbers" "打开/关闭行号")
       (Item "toggle-tabbar" "打开/关闭缓冲区标签栏 (似乎存在bug)")
       (Item "list-buffers" "列出所有缓冲区 (并可选择切换)")
       (Item "list-modes" "列出所有模式")
       (Item "lisp-mode" "切换至Common Lisp模式")
       (Item "scheme-mode" "切换至Scheme模式")
       (Item "list-color-themes" "列出所有主题 (并可选择切换)")
       (Item "load-theme" "加载主题")
       (Item "describe-bindings" "描述当前的快捷键绑定")
       
       )
   (H2 "配置")
   (Ul (Item "define-color-theme" "定义主题")
       (Item "define-command" "定义命令")
       (Item "define-key" "定义快捷键")
       
       )
   ))