#lang racket
(provide (all-defined-out))
(require SMathML)
(define $gcd (Mi "gcd"))
(define (&gcd a b)
  (appl $gcd a b))
(define $vert0 (Mo "&vert;" #:attr* '((lspace "0") (rspace "0"))))
(define (div a b)
  (: a $vert0 b))
(define $*0 (Mo "&#8270;" #:attr* '((lspace "0") (rspace "0"))))
(define i.<= (Mi "&le;"))
(define (&d x y)
  (appl $d x y))
(define $img (Mi "img"))
(define (&img f)
  (app $img f))
(define $exp (Mi "exp"))
(define (&exp x)
  (app $exp x))
(define $sup0 (Mi "sup"))
(define (&sup0 X)
  (ap $sup0 X))