#lang racket
(provide rss.xml)
(require SMathML/rss SMathML/xml racket/date)
(define (current-date-string #:format [format 'rfc2822])
  (date-display-format format)
  (date->string (current-date) #t))
(define rss.xml
  (RC #:title "愚者"
      #:link "https://alpha-beta-eta.github.io/"
      #:description "愚者的主页, 关于逻辑, 语言, 计算."
      (Item (Title "书籍推荐")
            (Description "作为书蠹的食物推荐")
            (Link "books.html"))
      (Item (Title "Linear Algebra (Hoffman &amp; Kunze) 翻译")
            (Link "linear_algebra.html")
            (Description "对于线性代数书籍Hoffman &amp; Kunze的翻译, 目前已完成了前7章.")
            (PubDate "Mon, 29 Jul 2024 23:37:23 +0800"))
      (Item (Title "Lectures on the Curry-Howard Isomorphism翻译")
            (Description "这是一本关于Curry-Howard同构的逻辑学书籍, 深入浅出. 目前我还没有翻译多少.")
            (Link "curry-howard.html")
            (PubDate "Sun, 21 Jan 2024 21:16:21 +0800"))
      (Item (Title "绘制数学图形")
            (Description "关于如何使用PostScript绘制数学图形的笔记")
            (Link "illustrations.html"))
      (Item (Title "程序设计的邀请")
            (Description "定位于初学者的程序设计教程, 尚未完工.")
            (Link "programming.html"))
      (Item (Title "LearningZIL笔记")
            (Description "ZIL是一种编写交互小说的DSL.")
            (Link "zil.html"))
      (Item (Title "The Ship of Theseus")
            (Description "个人对于忒修斯之船的理解")
            (Link "Ship-of-Theseus.html"))
      (Item (Title "Miscellaneous Notes")
            (Description "零碎的笔记, 主要和数学有关.")
            (Link "misc.html"))
      (Item (Title "Brzozowski导数")
            (Description "Brzozowski导数可用来进行句法分析, 尽管本文只是就正则语言而谈.")
            (Link "brzozowski.html"))
      
      ))