#lang racket
(provide useless.html)
(require SMathML)
(define useless.html
  (Prelude
   #:title "一些没用的笔记"
   #:css "styles.css"
   (H1 "一些没用的笔记")
   (columnize
    (H2 (A "The Ship of Theseus" #:attr* '((href "Ship-of-Theseus.html"))))
    (H2 (A "语义工程和PLT Redex笔记" #:attr* '((href "sewpr.html"))))
    (H2 (A "Proofs and Types第一章翻译"
           #:attr* '((href "notes/prot-ch1.pdf"))))
    (H2 (A "一些程序" #:attr* '((href "some_programs.html"))))
    (H2 (A "Miscellaneous Notes" #:attr* '((href "misc.html"))))
    (H2 (A "可计算性和计算复杂度" #:attr* '((href "jones.html"))))
    (H2 (A "证明与类型" #:attr* '((href "prot.html"))))
    (H2 (A "分析笔记" #:attr* '((href "analysis_notes.html"))))
    (H2 (A "线性代数笔记"
           #:attr* '((href "linear_algebra_notes.html"))))
    (H2 (A "范畴论笔记" #:attr* '((href "cat_awodey.html"))))
    (H2 (A "组合学笔记" #:attr* '((href "combinatorics_notes.html"))))
    (H2 (A "绘制数学图形" #:attr* '((href "illustrations.html"))))
    (H2 (A "计算机辅助设计的几何编程" #:attr* '((href "cad.html"))))
    (H2 (A "Topos: 逻辑的范畴分析" #:attr* '((href "topos.html"))))
    (H2 (A "Abel定理" #:attr* '((href "abel.html"))))
    (H2 (A "数学家学法语" #:attr* '((href "french.html"))))
    (H2 (A "Geometric Algebra (E. Artin) 翻译"
           #:attr* '((href "geometric_algebra.html"))))
    (H2 (A "函数式编程的论域论基础" #:attr* '((href "fp_domain.html"))))
    (H2 (A "结构证明论" #:attr* '((href "spt.html"))))
    (H2 (A "格论 (Birkhoff)" #:attr* '((href "lattices.html"))))
    (H2 (A "OPLSS" #:attr* '((href "oplss.html"))))
    (H2 (A "归纳定义" #:attr* '((href "induc.html"))))
    (H2 (A "元对象协议艺术" #:attr* '((href "mop.html"))))
    (H2 (A "Lem编辑器使用笔记" #:attr* '((href "lem_editor.html"))))
    (H2 (A "部分求值" #:attr* '((href "pe_jones.html"))))
    (H2 (A "SICM笔记" #:attr* '((href "sicm.html"))))
    (H2 (A "数据结构和算法笔记" #:attr* '((href "dsaa.html"))))
    (H2 (A "线性逻辑: 其句法和语义" #:attr* '((href "synsem.html"))))
    (H2 (A $lambda "演算: 其句法和语义" #:attr* '((href "lambda.html"))))
    (H2 (A "灵活软件设计" #:attr* '((href "sdf.html"))))
    (H2 (A "函数式微分几何" #:attr* '((href "fdg.html"))))
    (H2 (A "盲点" #:attr* '((href "blind.html"))))
    (H2 (A "高阶范畴逻辑导论" #:attr* '((href "hocl.html"))))
    (H2 (A "代数: 第0章" #:attr* '((href "algebra.html"))))
    (H2 (A "Common Lisp面向对象编程" #:attr* '((href "clos.html"))))
    (H2 (A "游戏设计" #:attr* '((href "game_design.html"))))
    (H2 (A "并行和顺序算法" #:attr* '((href "cmu15210.html"))))
    (H2 (A "命令式编程原理笔记" #:attr* '((href "cmu15122.html"))))
    (H2 (A "同伦类型论" #:attr* '((href "hott.html"))))
    (H2 (A "格论笔记" #:attr* '((href "lattice_theory_notes.html"))))
    (H2 (A "关于宏的笔记" #:attr* '((href "macro_notes.html"))))
    (H2 (A "证明论和逻辑复杂度" #:attr* '((href "proof_theory.html"))))
    (H2 (A "Kerodon翻译" #:attr* '((href "kerodon.html"))))
    (H2 (A "范畴逻辑和类型论" #:attr* '((href "cltt.html"))))
    (H2 (A "逻辑学习指南" #:attr* '((href "logic.html"))))
    
    )
   ))